config/routes.rb
Fandagr::Application.routes.draw do
resources :sessions, :only => [:new, :create]
match "logout" => "sessions#destroy", :as => "logout"
match "login" =>  "sessions#new", :as => "login"

resources :movies, :tickets

resources :users

get "/tickets/:movie_id/:time" => 'tickets#purchase'
post "/tickets/buy" => 'tickets#buy'


root :to => 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :duration, :name, :rating, :synopsis, :tickets
  has_many :tickets
  has_many :users, :through => :tickets
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :date, :movie_id, :seat, :time, :user_id, :seats
  belongs_to :movie
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :age, :name, :password, :username, :password_confirmation

  has_many :tickets
  has_many :movies, :through => :tickets

  validates :username, :uniqueness => true
  validates :age, :presence => { :message => "Age cannot be blank" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])

    else
      @current_user = nil

    end
  end

  helper_method :current_user

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def new
    @movie = Movie.new
  end

  def index
    @movies = Movie.all
    @tickets = Ticket.all
  end

  def create
    @movie = Movie.new(params[:movie])
    if @movie.save
      redirect_to movie_path
    else
      render :new
    end
  end


  def show
    @movie = Movie.find(params[:id])

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:username])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to movies_path
      else
        flash.now[:notice] = "Your email or password are not correct."
        render :new
      end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, :notice => "You're logged out."
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def purchase
    @tickets = Ticket.where(:movie_id => params[:movie_id]).where(:time => params[:time]).sort
  end

  def buy
    @ticket = Ticket.find(params[:ticket_id])
    @ticket.update_attributes(:user_id => current_user.id)
    render nothing: true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(params[:user])
    redirect_to root_path
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fancytime Theatre</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<div class="wrapper">

  <div class="sticky-bar"><span class="title"><a href="/">Fancytime Theatre</a></span>
    <% if current_user %>
      <p>You are logged in as <%= current_user.username %>
      <%= link_to("Log Out", logout_path) %></p>
    <% else %>
      <%= link_to("Sign Up", new_user_path) %>
      <%= link_to("Log In", new_session_path) %>
    <% end %>

  </div>
</div>
<body>

<%= yield %>

</body>
</html>

app/views/movies/index.html.erb
<div id="container">
  <h1>Movies for Sunday, July 14, 2013</h1>
  <% @movies.last(6).each do |movie| %>
  <div class="movies">
    <h2 class="movieName"><%= movie.name %></h2>
    <h3 class="rating"><%= movie.rating %></h2>
      <p class="synopsis"><%= movie.synopsis %></p>
      <p class="duration"><%= movie.duration %> minutes</p>
      <ul class="showtimes">
        <% movie.tickets.map(&:time).uniq.each do |ticket| %>
        <li><a href="/tickets/<%= movie.id %>/<%= ticket.strftime("%H:%M") %>"><%= ticket.strftime("%l:%Mpm") %></a></li><% end %>
      </ul>
  </div>
  <% end %>
</div>

app/views/movies/new.html.erb
<%= form_for @movie do |f| %>
<label>Name</label>
<%= f.text_field :name %>
<br>
<label>Rating</label>
<%= f.text_field :rating %>
<br>
<label>Duration</label>
<%= f.integer :duration %>
<br>
<label>Synopsis</label>
<%= f.text_field :synopsis %>
<br>
<%= f.submit %>
<% end %>

app/views/tickets/purchase.html.erb
<div id="container">
  <div class="theawrapper">
    <p class="tickMovieName"><%= @tickets.first.movie.name %></p>
    <p class="tickMovieDeets"><%= @tickets.first.date.strftime("%A, %b %d") %> at<%= @tickets.first.time.strftime(" %l:%Mpm") %>
    </p>
    <div class="theatre">
      <% @tickets.each do |ticket| %>
      <% if ticket.user == nil %>
          <div class="ticket available" id="<%= ticket.id %>"><%= ticket.seat %>
            <% link_to("S#{ticket.seat}", "#")%>
          </div>
        <% else%>
          <div class="ticket purchased" id="<%= ticket.id %>"><%= ticket.seat %>
            <% "S#{ticket.seat}" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
  <br>
  <br>
  <br>
  <br>
<%= form_for @user do |f| %>
  <label>Name</label>
  <%= f.text_field :name %>
  <label>Username</label>
  <%= f.text_field :username %>
  <label>Password</label>
  <%= f.password_field :password %>
  <label>Age</label>
  <%= f.number_field :age %>
  <label>Password Confirmation</label>
  <%= f.password_field :password_confirmation %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Patients#show</h1>
<p>Find me in app/views/patients/show.html.erb</p>
<p>
    <b>Name:</b>
    <%= @user.name %>
  </p>

  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Age:</b>
  <%= @user.age %>
</p>

<p>
  <b>Purchased Tickets:</b>
  <% @user.tickets.each do |ticket| %>
  <%= ticket.date %>
  <%= ticket.seat %>
  <%= ticket.time %>
  <%= ticket.movie.name %>
  <% end %>
</p>